### ISSUE TITLE
OAuth2Client  A task was canceld error

### ISSUE THREAD

**Issue by markovic987** [IdentityModel/Thinktecture.IdentityModel#129]
Hi,

I'm using OAuth2Client and Request Resource Owner flow to log into asp.net mvc app.
Everything works fine, but sometimes a got this error and cannot log into app: 
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Thinktecture.IdentityModel.Client.OAuth2Client.<RequestAsync>d__a.MoveNext()

My code is:
var client = new OAuth2Client(new Uri(TokenUri), clientId, clientSecret))

tokenResponse = await client.RequestResourceOwnerPasswordAsync(username, password, scope, additionalLoginData);    

I don't know how to resolve this error.
Please, if anybody have some clue about this, i would really appreciate.

**Comment by brockallen** [comment]
Sounds like the HTTP request timed out.

**Comment by markovic987** [comment]
Hi Allen,

Thank you for your reply.

I would not bother you anymore, but if you will have some time, maybe if
you can advise me what to do, i don't know what i'm doing wrong.
In generally, beside OAuth2Client, I'm using HttpClient, in this way:
 using (var client = new HttpClient())
            {
                client.Timeout = TimeSpan.FromMinutes(30);
                client.BaseAddress = new Uri(BaseUri);

                var response = await client.GetAsync(action);

                var result = new MethodResult<T>();
                if (response.IsSuccessStatusCode)
                {
                    result.IsSuccess = true;
                    result.Result = await response.Content.ReadAsAsync<T>();
                }
                else
                {
                    result.IsSuccess = false;
                    result.ErrorDescription = response.ReasonPhrase;
                }

                return result;
            }



Should I create HttpClient singleton or something like that?

Thanks.

Kind Regards,
Novak

**Comment by leastprivilege** [comment]
HttpClient is designed to be re-used. Don't put it into a using block.

**Comment by markovic987** [comment]
Big thanks Dominick. I will make singleton, but i was wondering
how to create one instance (singleton) of HttpClient , if i need to set
AccessToken oauth on header and those tokens are always different?

 httpClient.DefaultRequestHeaders.Authorization =
AuthenticationHeaderValue.Parse("Bearer " + accessToken);

It doesn't allow me to modify HttpClient, once it was created.

Thanks.

**Comment by leastprivilege** [comment]
You can construct an HttpRequestMessage instead and set the authZ header.

**Comment by markovic987** [comment]
Thanks Dominick, i will try that.

I don't know if this is correct,
for every login, we are doing:

var client = new OAuth2Client(new Uri(TokenUri), clientId, clientSecret);
tokenResponse = await client.RequestResourceOwnerPasswordAsync(username,
password, scope, additionalLoginData);

Is this correct approach in terms of performance, since we could have
potentially thousands of users, as we are building multi-tenant
applications?
