### ISSUE TITLE
Principal in my Authorization is not the same as User in my Web Api Controllers

### ISSUE THREAD

**Issue by tstone84** [IdentityModel/Thinktecture.IdentityModel#171]
I am using IdentityServerBearerTokenAuthentication, which is receiving an access token generated by IdentityServer3 and using IdentityModel for the ClaimsAuthorize attribute to handle Claims Authorization.  The issue i'm seeing is that the User in my controllers has my claims, however, the Principal in my AuthorizationContext that is passed into my AuthorizationContext.CheckAccess() method has no claims.  It seems that the Principal in my controllers is getting set after the AuthorizationManager.CheckAccess() is called.

As always, thanks for the help.

**Comment by tstone84** [comment]
It seems that I was using the incorrect nuget package. I have switched to Thinktecture.IdentityModel.Owin.ResourceAuthorization.WebApi.
I am now getting a NullReferenceException at: 
`at System.Net.Http.HttpRequestMessageExtensions.CheckAccessAsync(HttpRequestMessage request, IEnumerable`1 actions, IEnumerable`1 resources) in c:\ballen\github\thinktecture\Thinktecture.IdentityModel\source\Owin.ResourceAuthorization.WebApi\HttpRequestMessageExtensions.cs:line 36
   at Thinktecture.IdentityModel.WebApi.ResourceAuthorizeAttribute.CheckAccess(HttpRequestMessage request, Claim[] actions, Claim[] resources) in c:\ballen\github\thinktecture\Thinktecture.IdentityModel\source\Owin.ResourceAuthorization.WebApi\ResourceAuthorizeAttribute.cs:line 54
   at Thinktecture.IdentityModel.WebApi.ResourceAuthorizeAttribute.IsAuthorized(HttpActionContext actionContext) in c:\ballen\github\thinktecture\Thinktecture.IdentityModel\source\Owin.ResourceAuthorization.WebApi\ResourceAuthorizeAttribute.cs:line 49
   at System.Web.Http.AuthorizeAttribute.OnAuthorization(HttpActionContext actionContext)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.OnAuthorizationAsync(HttpActionContext actionContext, CancellationToken cancellationToken)`

**Comment by tstone84** [comment]
So, it seems this is caused by two extension methods for GetOwinContext() causing an ambiguous reference at runtime:
The type 'System.Net.Http.OwinHttpRequestMessageExtensions' exists in both 'IdentityServer3.dll' and 'System.Web.Http.Owin.dll'

I suppose I'll have to figure out a way to remove one of these.

**Comment by tstone84** [comment]
So, I believe I have resolved my issues around the ambiguous GetOwinContext, however, now, it simply gets null always.  I found this issue: [https://github.com/IdentityModel/Thinktecture.IdentityModel/issues/154](url) , but i'm hoping that's not the actual solution.

Any help would be greatly appreciated. I'm really hoping I've just missed some config somewhere.

Thanks!

**Comment by mattnhanson** [comment]
Having the same issue here. Any luck resolving the issue gracefully?

**Comment by tstone84** [comment]
@mattnhanson I ended up implementing my own custom authorize attribute and pulled the Principal from the RequestContext within my attribute.
